# Generated by Django 5.2.4 on 2025-07-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Precio total para planes con cantidad fija. Para planes personalizados, puede ser un precio base o 0.', max_digits=10, verbose_name='Precio del Plan'),
            preserve_default=False,
        ),
    ]
