# Generated by Django 5.2.4 on 2025-07-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plan_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio total para planes con cantidad fija. Para planes personalizados, puede ser un precio base o 0.', max_digits=10, null=True, verbose_name='Precio del Plan'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_produccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
