# Generated by Django 5.2.4 on 2025-07-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_plan_precio_alter_producto_costo_produccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL de la Imagen'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='color',
            field=models.CharField(blank=True, help_text='Color del tema (ej: amarillo, verde, rojo, purpura)', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='icon',
            field=models.CharField(blank=True, help_text='Nombre del ícono de Lucide (ej: Zap, Leaf, Heart, Beef,Star)', max_length=50),
        ),
    ]
