# Generated by Django 5.2.4 on 2025-07-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_producto_imagen_producto_imagen_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='es_destacado',
            field=models.BooleanField(default=False, help_text='Marca solo un menú como destacado. Este será el que se muestre en la web.', verbose_name='¿Es el menú destacado en la página principal?'),
        ),
    ]
