# Generated by Django 5.2.4 on 2025-07-29 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_menu_es_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Usuario de Instagram')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('calificacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación (1-5)')),
                ('aprobado', models.BooleanField(default=False, verbose_name='¿Aprobado para mostrar?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='ClienteProfile',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
