# Generated by Django 5.2.4 on 2025-07-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reseña_remove_detallepedido_pedido_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reseña',
            new_name='Resena',
        ),
    ]
